FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    git \
    libatlas-base-dev \
    libjasper-dev \
    libtiff5-dev \
    libjasper1 \
    libagg-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN mkdir -p /app/models /app/logs /app/videos

CMD ["python", "scripts/train.py"]
